### ISSUE TITLE
Rebase

### ISSUE THREAD

**Issue by weijia-cheng** [gsegol/jules-verne_in-search-of-the-castaways_j-b-lippincott#1]
I noticed three commits that have issues that need to be addressed with an interactive rebase. Let's take care of these first before the rest of the review.

0d69c479b50294581e283b5ecbf48492533c8359
4ba436d1eb4514cb687e1fee26e7b6ac13b0192b

These two commits combine an editorial change (changing a spelling) with a non-editorial change (adding language semantics). Editorial changes are not supposed to be mixed with non-editorial changes at all, even semantication. In an interactive rebase, these commits should be changed to remove the italics tags you added. I tested this in a local copy of your repository and I noticed that unfortunately this will involve working through some merge conflicts. Still, it's only two lines, so it's not too bad.

6c1b0043088e2957bcb494712c74188d3a5569cd

It appears to me that `Brittania` is actually the [printed spelling](https://babel.hathitrust.org/cgi/pt?id=wu.89006931323&view=2up&seq=407&skin=2021&q1=traces%20of%20the%20Brittania). This means that the change from `Brittania` to  `Britannia` is actually an editorial change to correct a printer's typo. This commit will have to be renamed to an editorial commit in the rebase (also the addition of the epub semantics will have to be removed like you did for the jilguero change).

I would recommend creating a backup of your repository before trying a rebase. (Also in the worst case, I have a fork of your repository.)

I'm not sure how familiar you are with rebasing, so I'll leave a quick walkthrough just in case. You'll begin by running:

```
git rebase --interactive 0d69c479b50294581e283b5ecbf48492533c8359~
```

Then you'll see a menu in your text editor like

```
pick 0d69c47 [Editorial] ch24 changed 'hilguero' to 'jilguero' and added spanish language tag
pick 035face added language tag in ch24
pick 4ba436d [Editorial] changed 'hilguero' to 'jilguero' and added language tag
pick 01704de added epub info and italics for book name in ch28
pick c3a3adf added missing epub info for Britannia in ch30
pick 7b6df25 added missing epub info for Britannia ch31
pick 7e6a0a4 replaced quotes w/ italics per 8.2.10.1 ch33, 35
pick ab84ad5 [Editorial] changed 'none the less' to one word, ch36
pick 4833116 corrected typo ch36 and added semantic info ch37
pick ecf8fbb added language tag and publication tag in ch38
pick 35ed7de [Editorial] changed 'pianiste' to 'pianist' ch38
pick 6c1b004 ch 40 changed 'Brittania' to 'Britannia' and added epub tag
pick cde1fcb corrected format in blockquote ch41
pick 22d6a3a ch45 changed i to em tag and deleted duplicate first paragraph
pick 3fd1f3d [Editorial] ch46 changed jury-mast to jurymast for consistency with other -mast and -sail
pick 36ebee3 ch47: added language tag; ch48, 49: replaced quotes w/ i tags for new words
pick 54f08f3 italicizednew words, ch50,51
pick f168b67 added italics ch52
pick a26eea5 removed extra quotes ch18, 19, 24, 25; added epub info ch 60; various typogrify fixes
pick 0731a01 removed extra '&gt;' ch50-52
pick 05c1b6b removed extra quotes ch24, added italics ch50, removed double space ch60
pick e418a27 changed epub-type to music.opera ch38
pick 1f864bb fixed a lang tag ch12 (from build --check-only)
```

On the lines for `0d69c47`, `4ba436d`, and `6c1b004`, you're going to replace `pick` with `edit`. Once you save and quit the text buffer, you'll start the interactive rebase and you'll be given the chance to revise those commits and rename them using `git commit --amend`. Unfortunately this will create merge conflicts and you'll have to work through the merge conflicts as well. Please let me know if you have any questions or need any more advice!

**Comment by gsegol** [comment]
There are more than a dozen instances of Britannia in the book,  The one instance of Brittania is a typo.  Calling this an editorial change  is really splitting hairs.  Ditto for the change from hilguero to jilguero to be done in two steps.  I would have liked to finish this project before calling quits, but I can't even get started with the rebasing (see attachment).  The Editor, Sublime Text is closed.  Perhaps someone else would like to take over this project?
<img width="783" alt="Screen Shot 2022-06-08 at 11 20 38" src="https://user-images.githubusercontent.com/65733749/172690152-befbd915-056d-436e-8316-e78a9c723df1.png">

**Comment by weijia-cheng** [comment]
I'm sorry Genevieve, I personally wouldn't care very much about any of those details but the guidelines we have are what we have. If you would like an alternative solution that involves more work, but doesn't involve rebasing, you could run

`git reset --hard 2382b106c1a21c10b9bf7ba27996bba5c8385521`

which would bring you to just before you made the first "jilguero" change and delete the commit history since then. You would then have to manually reapply the changes you've made in the last two weeks.

I'm not familiar with Mac development or Sublime Text so unfortunately I can't help with the rebase issue. I think if you can figure out the error and learn how to rebase, you can actually address these issues fairly quickly.

If absolutely none of these solutions appeals to you, I could do the rebase myself in a new repository to fix the history. For the remaining issues I find, you could fork my new repository and submit PRs. Let me know what you would like to do. I think it would be a shame if this project had to be abandoned for this!

**Comment by gsegol** [comment]
Weijia, I found the problem regarding the error noted above--something in the git config file.  Now I can at least display the list of commits as you showed above.  I will try to follow the process you indicated.  It may take me a few days. Thank you.
